### ISSUE TITLE
Remote service ingestion uses wrong proxy url

### ISSUE THREAD

**Issue by lucernae** [kartoza/least-cost-electrification-somalia#44]
@NyakudyaA discovered that remote ingestion doesn't work.
The screenshot suggest that the proxy url was misconfigured, so probably the internal docker container environment settings were not properly set up.

![remote-serv](https://user-images.githubusercontent.com/831865/140064085-25e6a5dd-d077-40e3-b789-b8164778f593.png)

@meomancer can you investigate this first?

**Comment by meomancer** [comment]
hi @lucernae 
PR : https://github.com/kartoza/least-cost-electrification-somalia/pull/46

The problem SITEURL on worker is not set because the entripoint.sh that is generating SITEURL is not called on run
entrypoint.sh is also called on Dockerfile, it seems that the image of django was generated while the env was not updated

maybe we can call the entrypoint.sh as docker entrypoint (as per PR)
or maybe we can rebuild the image

**Comment by lucernae** [comment]
The PR works nicely. Thanks @meomancer .

@NyakudyaA I deployed the fix and reharvesting the layer works.
